### ISSUE TITLE
Autofocus on input field on home page

### ISSUE THREAD

**Issue by tadman** [colby-swandale/rubyapi#110]
The `autofocus` property should be set on the home page input field. This means you can just start typing instead of having to click-engage the field.

**Comment by colby-swandale** [comment]
👍 A PR to add this would be 💯

**Comment by colby-swandale** [comment]
I've added this in https://github.com/colby-swandale/rubyapi/commit/0a489a56c254ffbeeb9ee99382b3c05d8db94fbe
